[parity]
chain = "C:/project/openethereum-windows-v3.1.0/demo-spec.json"
base_path = "C:/project/openethereum-windows-v3.1.0/data3"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "parity_accounts"]
cors = ["https://remix.ethereum.org/"]

[websockets]
port = 8453

[account]
password = ["C:/project/openethereum-windows-v3.1.0/node.pwds"]

[mining]
engine_signer = "0x7e700dca55b8a57108014059674b842907b6acdd"
reseal_on_txs = "none"