[parity]
chain = "C:/project/openethereum-windows-v3.1.0/demo-spec.json"
base_path = "C:/project/openethereum-windows-v3.1.0/data4"
[network]
port = 30304
[rpc]
port = 8544
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "parity_accounts"]
cors = ["https://remix.ethereum.org/"]

[websockets]
port = 8454

[account]
password = ["C:/project/openethereum-windows-v3.1.0/node.pwds"]

[mining]
engine_signer = "0x109089de9cd313cafa00b4a8ff65ae8749cb8637"
reseal_on_txs = "none"