[parity]
chain = "C:/project/openethereum-windows-v3.1.0/demo-spec.json"
base_path = "C:/project/openethereum-windows-v3.1.0/data1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "parity_accounts"]
cors = ["https://remix.ethereum.org/"]

[websockets]
port = 8451

[account]
password = ["C:/project/openethereum-windows-v3.1.0/node.pwds"]

[mining]
engine_signer = "0x1783a53a58b58827f39ad8eb8e7a4b857cd85429"
reseal_on_txs = "none"